spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/justhzd/learnrepository/
          search-paths: cloud/configfiles/
      label: master
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/