spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        service-id: service-config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
server:
  port: 8881